name: Access EC2 via Bastion Host using SSH Agent Forwarding

on:
  push: 
    branches:   
      - main  
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent 
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.BASTION_HOST_KEY }}
        
    - name: Copy private key to Bastion Host
      run: |
        echo "${{ secrets.PRIVATE_EC2_KEY }}" > private-ec2-key.pem
        scp -o StrictHostKeyChecking=no private-ec2-key.pem ubuntu@${{ secrets.BASTION_HOST_IP }}:~/private-ec2-key.pem
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_HOST_IP }} "chmod 400 ~/private-ec2-key.pem"
    
    - name: SSH into EC2 instance via Bastion Host
      run: |
       ssh -o StrictHostKeyChecking=no -A ubuntu@${{ secrets.BASTION_HOST_IP }} \
          "ssh -i ~/private-ec2-key.pem -o StrictHostKeyChecking=no ubuntu@${{secrets.DJANGO_IP}} 'echo Hello from GitHub Actions!;cd full-stack;git pull origin main'"
       ssh -o StrictHostKeyChecking=no -A ubuntu@${{ secrets.BASTION_HOST_IP }} \
          "ssh -i ~/private-ec2-key.pem -o StrictHostKeyChecking=no ubuntu@${{secrets.DJANGO_IP}} 'touch /home/ubuntu/full-stack/mysite/reload.flag'"
      
    - name: Clean up private key from Bastion Host 
      if: always()
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_HOST_IP }} "rm -f ~/private-ec2-key.pem"
