name: Access EC2 via Bastion Host using SSH Agent Forwarding

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into EC2 instance via Bastion Host
      run: |
        ssh -i ${{ secrets.Bastion_Host }} -o StrictHostKeyChecking=no -A -t ubuntu@3.37.167.42 \
          "ssh -i team-jun-2-privatekey.pem -o StrictHostKeyChecking=no ubuntu@10.0.142.240 'echo Hello from GitHub Actions!'"
