name: Run commands on EC2 via AWS Session Manager

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Run command on EC2 instance
      id: run-ssm-command
      run: |
        instance_id="i-0cc19beb035de8220"
        aws ssm send-command \
          --instance-ids "$instance_id" \
          --document-name "AWS-RunShellScript" \
          --comment "GitHub Actions command" \
          --parameters '{"commands":["echo Hello from GitHub Actions!"]}'
